# =========================================================================
# FUENTE
# =========================================================================
font_family      FiraCode Nerd Font Mono
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        14.0

# =========================================================================
# INTERFAZ Y VENTANAS
# =========================================================================
background_opacity 1.0
background_blur 1
window_padding_width 8
window_margin_width 2
hide_window_decorations no
confirm_os_window_close 0

# =========================================================================
# PESTAÑAS (TABS)
# =========================================================================
tab_bar_edge top
tab_bar_style powerline
tab_powerline_style slanted
tab_title_template "{index}: {title}"
active_tab_font_style bold-italic
inactive_tab_font_style normal

# =========================================================================
# COMPORTAMIENTO Y RENDIMIENTO
# =========================================================================
enable_audio_bell no
window_alert_on_bell no
copy_on_select yes
enabled_layouts tall,grid,horizontal,vertical,stack

# Enlaces
detect_urls yes
url_style straight
open_url_with default

# =========================================================================
# ATAJOS DE TECLADO
# =========================================================================
# Portapapeles
map ctrl+shift+c copy_to_clipboard
map ctrl+shift+v paste_from_clipboard

# Ventanas
map ctrl+enter new_window
map ctrl+shift+l next_window
map ctrl+shift+h previous_window
map ctrl+alt+h goto_layout horizontal
map ctrl+alt+v goto_layout vertical
map alt+shift+l next_layout
map ctrl+shift+z toggle_layout stack

# Pestañas
map ctrl+t new_tab
map ctrl+shift+w close_tab
map ctrl+shift+right next_tab
map ctrl+shift+left previous_tab
map ctrl+shift+n set_tab_title

# Recargar configuración
map ctrl+shift+r load_config_file

# =========================================================================
# TEMA Y COLORES
# =========================================================================
include oxocarbon.conf
